### ISSUE TITLE
missing presence show using venn diagram

### ISSUE THREAD

**Issue by wolski** [wolski/prolfqua#28]
Possible code
```
sum$missingness_per_condition()
tr <- 2
nrMiss <- tmp$data %>% pivot_wider(id_cols = "protein_Id", names_from = "bait", values_from = nrMeasured)
nrMiss[,2:4][nrMiss[,2:4] < tr] <- 0
nrMiss[,2:4][nrMiss[,2:4] >= tr] <- 1

upset(as.data.frame(nrMiss), order.by = "freq")
```

**Comment by serenygttrk** [comment]
Hello,
Comparing 2 groups from protein.txt file and sample size estimation:
I want to see non-finite values in the histogram but it is giving the error as below.
"Removed 88 rows containing non-finite values (`stat_density()`). "                                        In the following statisics, I continue receiving the error and instead of showing results from my 2 treatments, I get only "All" results. Could you help me with it please?

**Comment by wolski** [comment]
Hallo,

@serenygttrk 
I need more information to understand the problem. Can you please share your code and the input data?

Best regards
Witold

**Comment by wolski** [comment]
Upset Plot is implemented
