### ISSUE TITLE
Sample Rscript to process fragpipe lfqMBR outputfile

### ISSUE THREAD

**Issue by BenSamy2020** [wolski/prolfqua#56]
Greetings,

That you for providing this opensource package. By any chance would you be able to direct me to the location where the sample RScript is to process FragPipe LFQMBR output file?

Regards,
Ben

**Comment by wolski** [comment]
Hi Ben,

An example where the "combined_protein.tsv" produced by FragPipe is used as the input you can find here:
https://wolski.github.io/prolfquabenchmark/articles/BenchmarkFragPipeProteinIonStar.html

Since FragPipe also writes "MSstats.tsv" output, you can look at this vignette.
https://wolski.github.io/prolfquabenchmark/articles/BenchmarkFragPipeMSStats.html

Thanks for giving prolfqua a try.
Best
