### ISSUE TITLE
prolfqua_merged Vignette DIA-NN Output

### ISSUE THREAD

**Issue by abadgerw** [wolski/prolfqua#92]
@wolski Thank you for such a great package! I just wanted to see if you could point me in the right direction of using prolfqua_merged on my DIA-NN output file?

**Comment by abadgerw** [comment]
@wolski I just wanted to circle back and see if you had some insight into this query as I'd love to be able to use your fantastic tool?

**Comment by abadgerw** [comment]
@wolski Hope you are doing well. I  wanted to check in and see if you had a chance to review my query so that I may utilize your wonderful tool?

**Comment by wolski** [comment]
@abadgerw I'm sorry for not replying earlier. Unfortunately, since the end of July, the email notifications from Git Hub have been in my email client's spam folder. 

Did you have a look at this vignette?

https://fgcz.github.io/prolfqua/articles/CreatingConfigurations.html

Also, have a look at this discussion:
https://github.com/fgcz/prolfqua/discussions/85


Also, we now have a [bioarxv](https://www.biorxiv.org/content/10.1101/2024.10.09.617391v1)
 preprint, which describes a command line interface to prolfqua. 
There, you have out-of-the-box DIA-NN support.
